const eventDatails = [
  {
    name: "Treasure Hunt",
    staffCoordinate: "Dr.Arthy James & Dr.P.Manikandan",
    studentCoordinate: "Surya.P , Ajay.A & Thirumathi.C",
    desc: "A Game in which the organizers prepare a list defining specific items that need to be found, which the participants seek to gather or complete all items on the list, usually without purchasing them. Usually parcipants work in small teams, although the rules may allow",
    rules: [
      "Each Team should have 5 members.",
      "Each team should desiginated a team leader to communicated with organizers.",
      "The hunt will begin at designated starting point (LH-20).All teams must gather here for instructions.",
      "Clues will be provided at specified locations. Teams must find each clue in order to advancs.",
      "Each clue must be solved before moving to the next.",
      "There will be a set time limit for the entire hunt(30 minutes). Teams must returns to the starting point by this time.",
      "Teams may seek assistance from non-participants or use technology to find clues.",
      "Upon finding the final treasure , teams must return to the starting point for verification of completion.",
      "Prizes will be awarded to the first two teams to complete the hunt.",
      "Any rule violations may result in Disqualifications",
    ],
    prizes:
      "Participants certificate will be provide for all teams. Cash prize will be provided for 1st prize & 2nd prize",
    venue: "Lecture Hall-20",
    eventTime: "9:00AM - 11:00AM",
    registrationFee: "100/- per team",
  },
  {
    name: "Tech Talk Arena",
    staffCoordinate: "Mrs. Nagasri & Mrs. Shalini",
    studentCoordinate: "K.Vaishnavi , M.Krishnaveni & J.Parthiban",
    desc: "Tech Talk Arena refers to a platform or event space designed for discussion, presentation, and exchanges on technology related topics. These arenas are often interactive, allowing attendees to ask questions, participate in debates and network with like professionals.",
    rules: [
      "Don't copy from online",
      "Avoid clutter and unnecessary information",
      "Slides: 5 - 6 slides",
      "Time limit: 5 minutes",
      "Per team maximum ( 2 members )",
      "ID card is necessary for all the participants",
      "The participants should bring their own laptop",
    ],
    prizes:
      "1st Prize : 500/- , 2nd Prize : 250/- & Participation certificate for participants.",
    eventTime: "9:00AM - 11:00AM",
    registrationFee: "100/- per team",
  },
  {
    name: "Ballitastic blash",
    staffCoordinate: "Deepalakshmi & Subha rathi priya",
    studentCoordinate: "Kausalya T , Rajakumari C & Prathesha p",
    desc: "In the first round the player will tap the ball using a bat without moving from the place.The timing will be noted for how many minutes you tapped the ball.And in the next round a sketch of monkey will be there in the board and you should draw the tail for monkey.",
    rules: [
      " Solo participant is allowed",
      "The event will be engaged by using single hand only.",
      "while tapping the ball you should not move",
      "Ensure continuous drawing throughout the game",
      "The particiant should wear blindfold while drawing.",
    ],
    prizes:
      "1st prize:300/- , 2nd prize: 200 & *Certificates will be given for all participants",
    venue: "LH-16",
    eventTime: "9.00AM - 11.00Am",
    registrationFee: "30/-",
  },
  {
    name: "Dare and Ladder",
    staffCoordinate: "Girija.M ",
    studentCoordinate: "K.Divya , Aathidev V.M",
    desc: "In the 'Dare and Ladder' event, participants play a modified version of the traditional Snake and Ladder board game. The twist is that whenever a player lands on a snake's head and gets 'bitten,' they are required to perform a specific Dare before continuing. The dares can vary in difficulty or fun, adding an element of excitement and unpredictability to the game.",
    rules: [
      "Participants are required to register as individuals .Each batch will consist of 5 players competing against each other",
      "The game takes place on a custom Snake and Ladder board consisting of only 50 cells .",
      "The game begins with each participant rolling a single die, after which the traditional rules of Snake and Ladder apply.",
      "If a participant lands on a snake's head, they must face a challenge or dare,Completing the dare is mandatory.",
      "The participant who successfully navigates the board and reaches the final cell first will be declared the winner of the game.",
    ],
    prizes:
      "Winners 150/- , we are provided participants certificates fo all participants.",
    venue: "LH 17",
    eventTime: "9:00Am - 11:00AM",
    registrationFee: "50/-",
  },
  {
    name: "Byte & Brain Challenges",
    staffCoordinate: "Thiyagarajan , Rajalakshmi",
    studentCoordinate: "Keerthika.T , Malini.N & Tamilarasan.K",
    desc: "The 'Bytes and Brain Challenge' is a dynamic tech quiz designed to test participants knowledge on current techology trends, computer science concepts, and industrial insights. This engaging event consists of multiple rounds , including rapid-fire questions, puzzles, and practical knowledge assessments, aiming to challenge both the quik thinking and in-depth understanding of partcipants.",
    rules: [
      "Each team must have 3 members",
      "Mobiles phones or gadgets are not allowed during the quiz",
    ],
    prizes:
      "1st Prize: 500/- with framed certificate , 2nd Prize: 300/- with framed certificate & E-certificates for all participants",
    venue: "LH-13",
    eventTime: "11:00AM - 1:00AM",
    registrationFee: "100/- per team",
  },
  {
    name: "Echo-Echo",
    staffCoordinate: "Mr. Roshan",
    studentCoordinate: "R.Nagaraju , S.Sreenadh & S.Adeeb Hussain",
    desc: "ECHO-ECHO is an interactive performance event where participants will showcase their creativity by dubbing over a silent video played on the screen. The goal is to interpret and narrate the visuals through improvised dialogue and sound effects, bringing the story to life without the aid of the original audio. This event encourages teamwork, creativity, and spontaneity, allowing students to express their artistic flair in a fun and engaging manner…. ",
    rules: [
      "A per-selected silent video (duration: 3-5 minutes) will be show. Participants will receive the video tittle and theme in advance.",
      "Each team should consist of 3-4 members.",
      "Teams will have a maximum of 5 minutes to dub over the video.",
      "Participants are encouraged to improvise their dialogue and sound effects based on the visuals, promoting creativity and spontaneity.",
      "Performances will be evaluated based on: Creativity and originality , Synchronization with the visuals & Clarity and expression in dubbing",
      "ID card is necessary for all the participants.",
    ],
    prizes:
      "1st PRIZE: 500/- , 2ndPRIZE: 250/- & Participation certificate for participants.",
    registrationFee: "per team is 80/-",
  },
  {
    name: "Laugh Factory",
    staffCoordinate: "Priyanka & Rajaraman",
    studentCoordinate: "Sivashini.P , Shyamala.S",
    desc: "IN this event laugh factory, the participants will be given a topic on the spot to create a meme, either as a picture or video. So just bring your creativity and sense of humor!",
    rules: [
      "YOu should bring your own device( laptop, mobile )",
      "It's best to minimize mobile use when not needed.",
      "Participants is kindly limited to only two individuals.",
      "You are kindly allotted a duration of only 5 minutes.",
      "The meme is excepted to embody innovation and originally.",
    ],
    prizes:
      "1st Prize: 300/- , 2nd Prize; 200/- & certificates for all participants",
    venue: "LH-19",
    eventTime: "9:00AM - 11:00AM",
    registrationFee: "50/- per team",
  },
  {
    name: "Prompt.img",
    staffCoordinate: "Kayalvizhi",
    studentCoordinate: "Vijay Kumar , Shane Cardoz",
    desc: "Participants will be given a basic image, and they must use AI tools to recreate or enhance it creativity, maintining certain thermatic or stylic constraints.",
    rules: [
      "A time limit for participants to submit their recreated images.",
      "Participants can use any tools ( such as DALE-E, MidJourney, or Stable Diffusion ) to enhance or recreate the image.Participants must specify which tool they used and how they used it to achieve their result.",
      "A specific theme will be assigned at they very moment the event occurs. Ensure the AI generated recreation adheres to assigned sample image or theme.",
      "While AI is being used, participants must showcase creativity in how they prompt the AI, ensuring that no two recreation are exactly alike.",
      "Participants should the final image in a specified format ( e.g., PNG,JPEG ). Additionally, they should include the text prompt they used and a brief explanation of the creative choices made.",
      "Creativity: How unique is the recreation compared to the base image?",
      " Adherence to Theme: Does the image follow the given theme or challenge?",
      "Technical Skill: How well did the participants manipulation AI to achieve their desired result? ",
      "Aesthetic Quality: Is the final output visually appealing?",
      "Using someone else's work or images that aren't made by AI for your submission?That could get you disqualified, so be careful",
    ],
    prizes: "1st Prize: 500/- , 2nd Prize: 300/- ",
    venue: "First floor Data Science Lab.",
    eventTime: "11:00AM - 1:00PM",
    registrationFee: "50/- per head",
  },
  {
    name: "Tune Teasers",
    staffCoordinate: "Mrs. Kathirvizhi",
    studentCoordinate: "Archal Kumari , Nebinson.N",
    desc: "Tune Teasers is an fun, interactive game that challenges players on fronts in their knowledge of music. Player face-off in rounds where they need to identify songs and their artists.",
    rules: [
      "Team size: 3 (max)",
      "Players will have only 10 secs to answer after the tune has been played.",
      "Correct answers will be rewarded with 1 credit and None otherwise.",
      "If a player or team doesn't answer or answers incorrectly, the next team will get the chance to steal the credit.",
    ],
    prizes:
      "The winning team will be awarded with a cash prize of Rs.300 & each team will be given a Participation Certificate",
    registrationFee: "Rs.60",
  },
  {
    name: "Hunt the Bug",
    staffCoordinate: "Annthony Gillbert G & C Selva Uma",
    studentCoordinate: "Swathi & Urekha",
    desc: "A debugging event occurs when a program's execution results in unexpected behaviour or erors that deviated from the intended output.",
    rules: [
      "Two rounds will be conducted.",
      "Round 1:  MCQ type questions will be given.",
      "Round 2:  Set of program with errors will be given , parrticipats should correct the code and show the expected output.",
      "Languages to be known: C, Python, Java.",
      "Team size: 1 or 2 members",
    ],
    prizes:
      "1st Prize: Rs.500 , 2nd Prize: Rs.300 & All the participants will be provided with certificates.",
    venue: "First floor lab",
    eventTime: "9:00AM - 11:00AM",
    registrationFee: "Rs.100",
  },
  {
    name: "AdZap",
    staffCoordinate: "Mrs.Sundari",
    studentCoordinate: "Vishnu Priya.S , Steni Mary.G",
    desc: "AdZap is an exhilarating team based competition that tests creativity, quick thinking and marketing skills. Teams are presented with a random product on the spot and must develop a presuasive ad campaign that highlights the prodyct's features, benefits, and unique selling points, ultimately the judge ( or the audience ) of its value.",
    rules: [
      "Team size: 3 - 5 members",
      "Each team will randomly select a product from a designated pool.",
      "The competition will be held in 2 rounds.",
      "Round 1 : All 10 teams will participated.",
      "Round 2 : Only the top 5 teams selected by the judges from Round 1 will compete for the final prize.",
      "Teams are given 10 minutes to brainstorm and create their advertisement.",
      "Time limit :  3 minutes.",
      "Teams are not allowed to use external resources ( eg., internet, phones ) during the preparation time.",
      "A timer will be used to keeep track of preparation and presentation times. Teams must adhere to the allowed time.",
      "Following each presentation, there will be a 2 minutes Q & A session where judges and audience members can ask questions about the advertaisement and the product.",
      "No inappropriate language, offensive humor, or discriminatory content is allowed",
    ],
    prizes:
      "1st Prize: 500/- , 2nd Prize: 250/- & Certificate provided for all participants.",
    venue: "LH-18",
    eventTime: "9:00AM - 11:00AM",
    registrationFee: "100/- per team",
  },
  {
    name: "Innovative Expo",
    staffCoordinate: "Mr. Rajaram & Mrs. Lincy",
    studentCoordinate: "G.Loga Suthan , S.Kousalya & Vaidhe Eswari.M",
    desc: "The INNOVATIVE EXPO is a platform for students to showcase their innovative projects and ideas. This event aims to foster creativity, encourage collaboration and provide an opportunity for participants to present their work to a panel of judges and an audience of peers, faculty, and industry professionals.",
    rules: [
      "Open to all undergraduate and postgraduate students.",
      "Participants can register individually or in teams (maximum of 4 members per team).",
      "Projects must be original and developed by the participants.",
      "Each project should address a specific problem or need and propose a viable solution.",
      "Projects can be from any field of study, including but not limited to engineering, science, technology, and social sciences.",
      "Each team will be allotted a booth space to display their project.",
      "A poster presentation is mandatory, detailing the project’s objectives, methodology, results, and conclusions.",
      "Working models or prototypes are highly encouraged but not mandatory.",
      "Originality and uniqueness of the project.",
      "Soundness of the methodology and technical execution.",
      "Potential impact and applicability of the p Problem-Solving",
      "	ID card is necessary for all the participants.",
      "The participants should bring their own laptop.",
    ],
    prizes: "1st PRIZE: 500 ,2ndPRIZE: 250 ",
    venue: "",
    eventTime: "9:00AM - 11:00AM",
    registrationFee: "100/- per team",
  },
];

export default eventDatails;
